### ISSUE TITLE
[replan_controller] DELETE /projects/{projectId}/releases/{releaseId}/features does'n work

### ISSUE THREAD

**Issue by carlesf** [supersede-project/replan#1]
@antoninoCassarino says:

> DELETE /projects/{projectId}/releases/{releaseId}/features
> I got 200 OK status code, but the feature will not be removed from the release.

**Comment by carlesf** [comment]
Solved.
Bear in mind that if you want to delete more than one feature at a time, the format of  the request should be as follows:
`GET https://replan-project-carlesf.c9users.io/api/ui/v1/projects/1/releases/1/features?featureId=1,2`

**Comment by antoninoCassarino** [comment]
Tested. It works
