### ISSUE TITLE
[replan_controller] DELETE /projects/{projectId}/releases/{releaseId}/resources doesn't work

### ISSUE THREAD

**Issue by carlesf** [supersede-project/replan#2]
@antoninoCassarino says:

> DELETE /projects/{projectId}/releases/{releaseId}/resources
> I got 200 OK status code, but the resource will not be removed from the release.

**Comment by carlesf** [comment]
Solved.
Bear in mind that if you want to delete more than one resource at a time, the format of the request should be as follows:
`GET http://localhost/api/ui/v1/projects/1/releases/1/resources?ResourceId=1,2`

**Comment by antoninoCassarino** [comment]
Tested. It works
