### ISSUE TITLE
[replan_controller] dependencies information in features

### ISSUE THREAD

**Issue by carlesf** [supersede-project/replan#4]
@antoninoCassarino says:

>  I forgot to mention during last meeting that I need dependencies information in the features.

**Comment by carlesf** [comment]
That information is provided whenever you call 
`GET /api/ui/v1/projects/1/features` or `GET /api/ui/v1/projects/1/features/3`

In this latter case you should get: (Note that feature 3 depends on 1 and 2)

`{
  "id": 3,
  "code": 334,
  "name": "Enrollment refactoring",
  "description": "Bla, bla, bla",
  "effort": null,
  "deadline": "2016-10-01",
  "priority": 3,
  "required_skills": [],
  "depends_on": [
    {
      "id": 1,
      "code": 111,
      "name": "Fix auto upload",
      "description": "Bla, bla, bla",
      "effort": null,
      "deadline": "2016-09-26",
      "priority": 5,
      "release": {
        "release_id": 1
      }
    },
    {
      "id": 2,
      "code": 222,
      "name": "New login",
      "description": "Bla, bla, bla",
      "effort": null,
      "deadline": "2016-09-28",
      "priority": 4,
      "release": {
        "release_id": 1
      }
    }
  ],
  "release": "pending"
}`

**Comment by carlesf** [comment]
I realized that the deletion of dependencies doesn't work properly

**Comment by carlesf** [comment]
Solved.
Bear in mind that if you want to delete more than one dependecy at a time, the format of the request should be as follows:
`DELETE /api/ui/v1/projects/1/features/3/dependencies?feature_id=1,4`

**Comment by antoninoCassarino** [comment]
The feature depends_on array is empty, please check again :-)

**Comment by carlesf** [comment]
I forgot to put some sample dependencies in the script that populates the DB. Try to add them by yourself using the POST /projects/{projectId}/features/{featureId}/dependencies request
