### ISSUE TITLE
[replan_controller] deleteSkillsFromResource

### ISSUE THREAD

**Issue by antoninoCassarino** [supersede-project/replan#5]
update  deleteSkillsFromResource like in 1.

The actual status:
1.  DELETE /projects/1/resources/5/skills?skillId=3,1 I get 500 error
2.  DELETE /projects/1/resources/5/skills?skillId[0]=3&skillId[1]=1 I get 200 is OK

**Comment by carlesf** [comment]
Now DELETE /projects/1/resources/5/skills?skillId=3,1 should work (after re-deployment, of course)
